openapi: 3.0.3
info:
  title: hacky rest api
  description: REST API for test
  version: 3.0.0
security:
  - bearer:
      []
paths:
  /character:
    post:
      operationId: createCharacter
      summary: Create character
      description: Creates character
      tags:
        - Characters
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Character"
        description: Payload
        required: true
      responses:
        "200":
          description: Created Character
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  "/character/list/{userId}":
    get:
      operationId: listCharacters
      summary: Lists characters
      description: Lists Characters
      tags:
        - Characters
      parameters:
        - name: userId
          required: true
          in: path
          description: user id
          schema:
            type: string
      responses:
        "200":
          description: List of characters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  "/character/{characterId}":
    get:
      operationId: findCharacter
      summary: Find character
      description: Finds character by id
      tags:
        - Characters
      parameters:
        - name: characterId
          required: true
          in: path
          description: character id
          schema:
            type: string
      responses:
        "200":
          description: A created news article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    delete:
      operationId: deleteCharacter
      summary: Deletes a character
      description: Deletes a character
      tags:
        - Characters
      parameters:
        - name: characterId
          required: true
          in: path
          description: character id
          schema:
            type: string
      responses:
        "200":
          description: Deleted successfully character
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
components:
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Character:
      type: object
      required:
        - id
        - name
        - userId
        - statsId
      properties:
        id:
          type: string
        name:
          type: string
        userId:
          type: string
        statsId:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    InternalServerError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Forbidden:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    BadRequest:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    NotImplemented:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    NotFound:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
