openapi: 3.0.3
info:
  title: Test rest api
  description: REST API for test
  version: 3.0.0
security:
  - bearer:
      []
paths:
  /newsArticles:
    post:
      operationId: createNewsArticle
      summary: Create news article
      description: Creates news article
      tags:
        - NewsArticles
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewsArticle"
        description: Payload
        required: true
      responses:
        "200":
          description: Created news article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsArticle"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    get:
      operationId: listNewsArticles
      summary: Lists news articles
      description: Lists news articles
      tags:
        - NewsArticles
      responses:
        "200":
          description: List of news articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NewsArticle"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  "/newsArticles/{newsArticleId}":
    get:
      operationId: findNewsArticle
      summary: Find news article
      description: Finds news article by id
      tags:
        - NewsArticles
      parameters:
        - name: newsArticleId
          required: true
          in: path
          description: news article id id
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A created news article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsArticle"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    put:
      operationId: updateNewsArticle
      summary: Update news article
      description: Updates news article
      tags:
        - NewsArticles
      parameters:
        - name: newsArticleId
          required: true
          in: path
          description: news article id id
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewsArticle"
        description: Payload
        required: true
      responses:
        "200":
          description: Updated news article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsArticle"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    delete:
      operationId: deleteNewsArticle
      summary: Delete news article
      description: Deletes news article
      tags:
        - NewsArticles
      parameters:
        - name: newsArticleId
          required: true
          in: path
          description: news article id id
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: No content to indicate successful delete
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /characters:
    post:
      operationId: createCharacter
      summary: Create new character
      description: Creates new character
      tags:
        - Characters
      parameters:
        - in: path
          name: character 
          description: character object
          required: true
          schema:
            $ref: "#/components/schemas/Character"
      responses:
        "200":
          description: Created Character
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
    get:
      operationId: listCharacters
      summary: Lists characters
      description: Lists Characters
      tags:
        - Characters
      responses:
        "200":
          description: List of characters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Character"
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        "403":
          description: Attempted to make a call with unauthorized client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
components:
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    NewsArticle:
      type: object
      required:
        - title
        - contents
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        contents:
          type: string
        imageUrl:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    Character:
      type: object
      required:
        - name
        - level
        - experience
      properties:
        id:
          type: string
        name:
          type: string
        level:
          type: integer
          format: int64
        experience:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    InternalServerError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Forbidden:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    BadRequest:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    NotImplemented:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    NotFound:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
