/**
 * hacky rest api
 * REST API for test
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { Stat } from './stat';


export interface FullCharacter { 
    id: string ;
    name: string ;
    userId: string ;
    statsId: string ;
    readonly createdAt: Date  | null;
    readonly updatedAt: Date  | null;
    level: number ;
    experience: number ;
}    


