/**
 * hacky rest api
 * REST API for test
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface HttpError { 
    code: number  | null;
    message: string  | null;
}    

export interface HttpErrorOpt { 
    code?: number;
    message?: string;
}
